blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'), # homepage
    path('post/<int:blog_post_id>', views.blog_post_detail, name='blog_post_detail'), # blog post detail page
    path('archives/<int:year>/<int:month>', views.archive, name='archive'), # archived blog posts
    path('categories/<int:cate_id>', views.category, name='category'), # category's blog posts
    path('tags/<int:tag_id>', views.tags, name='tag'), # tag's blog posts
]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'

urlpatterns = [
    path('comments/<int:blog_post_id>', views.submit_comment, name='submit_comment'), # comment's detail
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # urls for blog app
    path('', include('blog.urls')),

    # urls for comment app
    path('', include('comment.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown2


class Tag(models.Model):
    """
    Model for tags
    """
    tag_name = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签列表'

    def __str__(self):
        return '%s' % self.tag_name


class Category(models.Model):
    """
    Model for categories
    """
    category_name = models.CharField(max_length=32)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类列表'

    def __str__(self):
        return '%s' % self.category_name


class BlogPost(models.Model):
    """
    Model for a blog post
    """
    # basic fields
    title = models.CharField(max_length=64)
    text = models.TextField()
    excerpt = models.CharField(max_length=128, null=True, blank=True, default='')
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # relational fields
    # ONE user can post MANY blog posts and ONE specific blog post belongs to ONE user
    author = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, default='Admin')

    # ONE blog post can have MANY tags and ONE tag can filter MANY blog posts
    tags = models.ManyToManyField(to=Tag, blank=True)

    # ONE blog post belongs to ONE category and ONE category contains MANY blog posts
    category = models.ForeignKey(to=Category, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章列表'
        ordering = ['-created_at']  # set the default ordering field

    def save(self, *args, **kwargs):
        """
        rewrite the save() method to set a default excerpt field
        """
        if self.excerpt is None:
            # if excerpt is empty, then an automatic excerpt will be generated
            # to covert markdown syntax into html tags
            md2html = markdown2.markdown(
                self.text,
                extras=[
                    'fenced-code-blocks',
                    'code-color',
                    'code-friendly',
                ],
            )
            # remove html tags and
            # fetch the first 64 characters from the main text
            self.excerpt = strip_tags(md2html)[:64]

        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        """
        get blog post's url
        """
        return reverse('blog:blog_post_detail', kwargs={'blog_post_id': self.id})

comment/models.py
from django.db import models
from django.utils.timezone import now
from blog.models import BlogPost


class Comment(models.Model):
    """
    Model for a comment
    """
    username = models.CharField(max_length=64)
    email = models.EmailField()
    url = models.URLField(blank=True)
    text = models.TextField()
    created_at = models.DateTimeField(default=now)

    # ONE blog posts contains MANY comments and ONE comment only belongs to ONE specific blog post
    blog_post = models.ForeignKey(to=BlogPost, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论列表'
        ordering = ['-created_at'] # ordering the comments with desc

    def __str__(self):
        return '{}: {}'.format(self.username, self.text[:10])

comment/forms.py
from django import forms
from comment.models import Comment


class CommentForm(forms.ModelForm):
    """
    Create a comment form
    """
    class Meta:
        model = Comment
        fields = ['username', 'email', 'url', 'text']

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import BlogPost, Category, Tag
from django.utils.text import slugify
import markdown2


def index(request):
    """
    This function fetch all blog posts and render the index.html which is the main region of base.html
    """
    blog_posts = BlogPost.objects.all()

    context = {
        'website_title': 'White & Black',
        'blog_posts': blog_posts,
    }

    return render(request, 'blog/index.html', context)


def blog_post_detail(request, blog_post_id):
    """
    get the content of a specific blog post
    """
    # to fetch the blog post
    blog_post = get_object_or_404(BlogPost, pk=blog_post_id)

    # convert markdown into html tags with code friendly css style
    md2html = markdown2.markdown(
        blog_post.text,
        extras=[
            'fenced-code-blocks',
            'code-color',
            'code-friendly',
            'toc'
        ],
    )
    blog_post.text = md2html # html tags
    blog_post.toc = md2html.toc_html # table of content

    context = {
        'website_title': 'White & Black',
        'blog_post': blog_post,
    }

    return render(request, 'blog/blog_post_detail.html', context)


def archive(request, year, month):
    """
    according to the year and month to show blog posts
    """
    # to fetch blog posts with specific year and month
    blog_posts = BlogPost.objects.filter(created_at__year=year, created_at__month=month)

    context = {
        'website_title': 'White & Black',
        'blog_posts': blog_posts,
    }

    return render(request, 'blog/index.html', context)


def category(request, cate_id):
    """
    to show all blog posts with specific category id
    """
    # to fetch the category id and to filter the blog posts with this id
    cate = get_object_or_404(Category, pk=cate_id)
    blog_posts = BlogPost.objects.filter(category=cate)

    context = {
        'website_title': 'White & Black',
        'blog_posts': blog_posts,
    }

    return render(request, 'blog/index.html', context)


def tags(request, tag_id):
    """
    to show all blog posts with specific tag id
    """
    # to search the tag with the specific tag id and return all the blog posts with this tag
    tag = get_object_or_404(Tag, pk=tag_id)
    blog_posts = BlogPost.objects.filter(tags=tag)

    context = {
        'website_title': 'White & Black',
        'blog_posts': blog_posts,
    }

    return render(request, 'blog/index.html', context)

comment/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from blog import models
from comment import forms
from django.views.decorators.http import require_POST


@require_POST
def submit_comment(request, blog_post_id):
    """
    submit the comment form with a specific blog post
    """
    blog_post = get_object_or_404(models.BlogPost, pk=blog_post_id)

    form = forms.CommentForm(request.POST) # filled the form with POST data

    if form.is_valid():
        # the form data is legal and bind with the blog post
        new_comment = form.save(commit=False)
        new_comment.blog_post = blog_post
        new_comment.save()

        # successfully send a comment on current post
        messages.add_message(request, level=messages.SUCCESS, message='评论发表成功！', extra_tags='success')

        return redirect(blog_post)

    context = {
        'blog_post': blog_post,
        'form': form,
    }

    # failed to send a comment
    messages.add_message(request, level=messages.ERROR, message='评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')

    return render(request, 'comments/preview.html', context)

templates/base.html
{% load static %}
{% load blog_extras %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ website_title }}</title>

        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- css -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
        <!-- highlighting code -->
        <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
        <style>
        .codehilite {
          padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
          -webkit-touch-callout: none;
          -webkit-user-select: none;
          -khtml-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;

          text-align: center;
          color: #ccc;
          border-right: 1px solid #CCC;
          vertical-align: top;
          padding-right: 5px;
        }

        .hljs-ln-n {
          width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
          padding-left: 10px;
          white-space: pre;
        }
        </style>

        <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </head>

    <body>

        <!-- Website title and Homepage -->
        <div class="container">
            <header id="site-header">
                <div class="row">
                    <!-- Website title -->
                    <div class="col-md-4 col-sm-5 col-xs-8">
                        <div class="logo">
                            <h1><a href="{% url 'blog:index' %}">{{ website_title }}</a></h1>
                        </div>
                    </div><!-- col-md-4 -->

                    <div class="col-md-8 col-sm-7 col-xs-4">
                        <!-- Nav Menu-->
                        <nav class="main-nav" role="navigation">
                            <!-- empty area between title and nav -->
                            <div class="navbar-header">
                                <button type="button" id="trigger-overlay" class="navbar-toggle">
                                    <span class="ion-navicon"></span>
                                </button>
                            </div>

                            <!-- Nav menu button -->
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                                    <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                                    <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                                    <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </nav>

                        <!-- Search Button -->
                        <div id="header-search-box">
                            <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                            <div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="#">
                                    <input type="search" placeholder="搜索" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div>
                        </div><!-- col-md-8 -->
                    </div>
            </header>
        </div>

        <!-- Main Content Region -->
        <div class="content-body">
            <div class="container">
                <div class="row">
                    <!-- Blog posts region -->
                    <main class="col-md-8">
                        {% block main_contain_region %}
                        {% endblock %}

                        {% block comment_region %}
                        {% endblock %}
                    </main>

                    <!-- Sidenav region -->
                    <aside class="col-md-4">
                        {% block blog_post_toc %}
                        {% endblock %}

                        {% show_recent_blog_posts %}
                        {% show_archives %}
                        {% show_tags %}
                        {% show_categories %}

                        <div class="rss">
                            <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                        </div>
                    </aside>
                </div>
            </div>
        </div>

        <!-- Footer Region -->
        <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                    <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                            target="_blank" title="模板之家">模板之家</a>
                        - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                    </p>
                </div>
            </div>
            </div>
        </footer>

        <!-- Mobile Nav Menu -->
        <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="#">博客</a></li>
                <li><a href="#">关于</a></li>
                <li><a href="#">联系</a></li>
            </ul>
        </nav>
        </div>

        <!-- others -->
        <script src="{% static 'blog/js/script.js' %}"></script>

        <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
        <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
        <script>
            hljs.initHighlightingOnLoad();
            hljs.initLineNumbersOnLoad();
        </script>
    </body>
</html>

templates/blog/base.html
{% load static %}
{% load blog_extras %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ website_title }}</title>

        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- css -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
        <!-- highlighting code -->
        <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
        <style>
        .codehilite {
          padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
          -webkit-touch-callout: none;
          -webkit-user-select: none;
          -khtml-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;

          text-align: center;
          color: #ccc;
          border-right: 1px solid #CCC;
          vertical-align: top;
          padding-right: 5px;
        }

        .hljs-ln-n {
          width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
          padding-left: 10px;
          white-space: pre;
        }
        </style>

        <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js'%}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    </head>

    <body>

        <!-- Website title and Homepage -->
        <div class="container">
            <header id="site-header">
                <div class="row">
                    <!-- Website title -->
                    <div class="col-md-4 col-sm-5 col-xs-8">
                        <div class="logo">
                            <h1><a href="/">{{ website_title }}</a></h1>
                        </div>
                    </div><!-- col-md-4 -->

                    <div class="col-md-8 col-sm-7 col-xs-4">
                        <!-- Nav Menu-->
                        <nav class="main-nav" role="navigation">
                            <!-- empty area between title and nav -->
                            <div class="navbar-header">
                                <button type="button" id="trigger-overlay" class="navbar-toggle">
                                    <span class="ion-navicon"></span>
                                </button>
                            </div>

                            <!-- Nav menu button -->
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11"><a href="#" data-hover="首页">首页</a></li>
                                    <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                                    <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                                    <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </nav>

                        <!-- Search Button -->
                        <div id="header-search-box">
                            <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                            <div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="#">
                                    <input type="search" placeholder="搜索" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div>
                        </div><!-- col-md-8 -->
                    </div>
            </header>
        </div>

        <!-- Main Content Region -->
        <div class="content-body">
            <div class="container">
                <div class="row">
                    <!-- Blog posts region -->
                    <main class="col-md-8">
                        {% block main_contain_region %}
                        {% endblock %}
                        {% block comment_region %}
                        {% endblock %}
                    </main>

                    <!-- Sidenav region -->
                    <aside class="col-md-4">
                        {% block blog_post_toc %}
                        {% endblock %}

                        {% show_recent_blog_posts %}
                        {% show_archives %}
                        {% show_tags %}
                        {% show_categories %}

                        <div class="rss">
                            <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                        </div>
                    </aside>
                </div>
            </div>
        </div>

        <!-- Footer Region -->
        <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                    <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                            target="_blank" title="模板之家">模板之家</a>
                        - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                    </p>
                </div>
            </div>
            </div>
        </footer>

        <!-- Mobile Nav Menu -->
        <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="#">首页</a></li>
                <li><a href="#">博客</a></li>
                <li><a href="#">关于</a></li>
                <li><a href="#">联系</a></li>
            </ul>
        </nav>
        </div>

        <!-- others -->
        <script src="{% static 'blog/js/script.js' %}"></script>

        <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
        <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
        <script>
            hljs.initHighlightingOnLoad();
            hljs.initLineNumbersOnLoad();
        </script>
    </body>
</html>

templates/blog/blog_post_detail.html
{% extends 'base.html' %}

{% load comments_extras %}


{% block main_contain_region %}
    {% if blog_post %}
        <article class="post post-{{ blog_post.id }}">
            <header class="entry-header">
                <h1 class="entry-title">{{ blog_post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' blog_post.category_id%}">{{ blog_post.category.category_name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date">{{ blog_post.created_at }}</time></a></span>
                <span class="post-author"><a href="#">{{ blog_post.author }}</a></span>
                <span class="comments-link"><a href="{{ blog_post.get_absolute_url }}#comment-area">{{ blog_post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ blog_post.views }} 阅读</a></span>
                <span class="likes-count"><a href="#">{{ blog_post.likes }} 喜欢</a></span>
            </div>
            </header>

            <div class="entry-content clearfix">
                {{ blog_post.text|safe }}
            </div>
        </article>
    {% endif %}
{% endblock %}

{% block comment_region %}
    <!-- Comment region -->
    <section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
        {% show_comment_form blog_post %}
        {% comment_list blog_post.id %}
    </section>
{% endblock %}

{% block blog_post_toc %}
    <!-- table of content -->
    {% if blog_post.toc %}
        <div class="widget widget-content">
            <h3 class="widget-title">文章目录</h3>
            <div class="toc">{{ blog_post.toc|safe }}</div>
        </div>
    {% endif %}
{% endblock %}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for datetime in datetime_list %}
        <li>
            <a href="{% url 'blog:archive' datetime.year datetime.month %}">{{ datetime.year }} 年 {{ datetime.month }} 月</a>
        </li>
        {% empty %}
            暂无归档！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
  <h3 class="widget-title">分类</h3>
  <ul>
    {% for category in category_list %}
      <li>
        <a href="{% url 'blog:category' category.id %}">{{ category.category_name }} <span class="post-count">(13)</span></a>
      </li>
    {% empty %}
      暂无分类！
    {% endfor %}
  </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
        <ul>
            {% for blog_post in recent_post_list %}
            <li>
                <a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a>
            </li>
            {% empty %}
                暂无文章！
            {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
  <h3 class="widget-title">标签云</h3>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{% url 'blog:tag' tag.id %}">{{ tag.tag_name }}</a>
      </li>
    {% empty %}
      暂无标签！
    {% endfor %}
  </ul>
</div>

templates/blog/index.html
{% extends 'blog/../base.html' %}

{% block main_contain_region %}
    {% for blog_post in blog_posts %}
        <!-- Blog post items -->
        <article class="post post-{{ blog_post.id }}">
            <!-- Blog post info -->
            <header class="entry-header">
                <!-- Blog post title -->
                <h1 class="entry-title">
                    <a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a>
                </h1>

                <div class="entry-meta">
                    <!-- Blog post category -->
                    <span class="post-category"><a href="#">{{ blog_post.category }}</a></span>
                    <!-- Blog post published date -->
                    <span class="post-date"><a href="#"><time class="entry-date" >{{ blog_post.created_at }}</time></a></span>
                    <!-- Blog post author -->
                    <span class="post-author"><a href="#">{{ blog_post.author }}</a></span>
                    <!-- Blog post comments-->
                    <span class="comments-link"><a href="#">{{ blog_post.comments }} 评论</a></span>
                    <!-- Blog post views-->
                    <span class="views-count"><a href="#">{{ blog_post.views }} 阅读</a></span>
                    <!-- Blog post likes-->
                    <span class="likes-count"><a href="#">{{ blog_post.likes }} 喜欢</a></span>
                </div>
            </header>
            <!-- Blog post abstract and detail link -->
            <div class="entry-content clearfix">
                <p>{{ blog_post.excerpt }}....</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ blog_post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post"><h1>暂时还没有发布的文章！</h1></div>
    {% endfor %}
{% endblock %}

templates/comments/inclusions/_comment_list.html
<div class="comment-list-panel">
<h3>评论列表，共 <span>{{ total_cnt_comment }}</span> 条评论</h3>
    {% for comment in comment_list %}
    <ul class="comment-list list-unstyled">
        <li class="comment-item">
            <span class="nickname">{{ comment.username }}</span>
            <time class="submit-date" >{{ comment.created_at }}</time>
            <div class="text">
                {{ comment.text|linebreaks }}
            </div>
        </li>
    </ul>
    {% empty %}
    {% endfor %}
</div>

templates/comments/inclusions/_form.html
<form action="{% url 'comment:submit_comment' blog_post.id %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.username.id_for_label }}">{{ form.username.label }}：</label>
      {{ form.username }}
      {{ form.username.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>    <!-- row -->
</form>

templates/comments/preview.html
{% extends 'blog/../base.html' %}
{% load comments_extras %}

{% block comment_region %}
    {% show_comment_form blog_post form %}
{% endblock %}